### ISSUE TITLE
Systray icon doesn't show new messages anymore

### ISSUE THREAD

**Issue by shagath** [sindresorhus/caprine#1028]
It just stays grey. I love how the app can be hidden now to systray(was waiting for that feature a lot) but no indicators for a new message. It used to go blue iirc.

---

Caprine 2.34.0
Electron 5.0.6
win32 10.0.18945
Locale: en-US

**Comment by riverstore** [comment]
I have same problem from version 2.48.0. And sometime, when I use Caprine to chat with my friend, I seen the message but on his side, Messenger don't indicate that I read message.

Anyone know the problem please help. Thanks a lot.
---

Caprine 2.49.0
Electron 10.1.1
win32 10.0.18362
Locale: en-US

**Comment by dusansimic** [comment]
I think that the original issue is probably fixed by this time since it works on my machine but regarding your problem @riverstore, it could be that you have some unread message down in contact list. If that is not the case please let me know. If you know some specific way that I could reproduce this issue, that would be great.

**Comment by riverstore** [comment]
I'm using the latest version, but the problem still not fixed. And I may familiar with it ^^

**Comment by dotpointer** [comment]
The system tray icon does not change when a new message is available here either, it is always grey. But this is on Debian 10 MATE.

Caprine 2.51.2
Electron 10.1.5
linux 4.19.0-13-amd64
Locale: sv

**Comment by dusansimic** [comment]
Facebook released a new Messenger UI for web which broke most of the Caprine features. Fixes are in progress for all issues including this one. You can see what is fixed so far [here](https://github.com/sindresorhus/caprine/pull/1514). Fixes will be available once that PR is merged.

**Comment by dotpointer** [comment]
While waiting for this to be fixed I found a workaround for Linux desktops by displaying relevant part of the Caprine main window title on a panel on the desktop.

In case a new message appear, then a part of the Caprine window title will be shown on the panel, like:
"(<messages>) Messenger" or "<name> has sent a message"

Script to extract data from the window title, `xwininfo` is required for this to work:
```
#!/bin/bash
WNDTITLE=$(xwininfo -root -children|grep '"caprine" "Caprine"'|head -n1);
WNDTITLE=$(echo $WNDTITLE|sed 's/.*[0-9]x[0-9a-z]* "\(.*\)": .*/\1/');
if [ "$WNDTITLE" != "Messenger" ] && [ "$WNDTITLE" != "caprine" ]; then
  echo "$WNDTITLE";
else
  echo " ";
fi
```

Instructions for Debian 10 with MATE Desktop:
1. Put the above script in a suitable location, for example /home/<your-username>/caprine-checker.sh.
2. Make it executable, chmod +x /home/<your-username>/caprine-checker.sh.
3. Right-click on a panel somewhere, choose Add to panel..., then Command.
4. You will get a clock in the panel, right click on it, choose Settings.
5. Command: /opt/scripts/caprine-checker.sh, Interval: 15 (or what you want), Maximum width: 20 (or what you want).
6. Click Close.
