### ISSUE TITLE
Dark mode not set on startup

### ISSUE THREAD

**Issue by JoelFeiner** [sindresorhus/caprine#1525]
I am using Caprine built from master and installed locally.

When I start Caprine, I do not get dark mode, even though the box is checked in the menu. If I uncheck the box and then check the box again, it switches to dark mode.

**Comment by dusansimic** [comment]
Hi! Could you please explain your build process? On what platform are you and what target package did you build? Does that happen every time you start Caprine? Are there any error messages in DevTools?

**Comment by JoelFeiner** [comment]
> Hi! Could you please explain your build process? On what platform are you and what target package did you build? Does that happen every time you start Caprine? Are there any error messages in DevTools?

I'm on Ubuntu 20.04. I built for Linux using `npm run dist`. I had to modify it not to try to build for Windows or MacOS X since I don't have the tools for that.

It happens every time I start Caprine. There are no messages in the console when I bring up dev tools.

**Comment by supra107** [comment]
In my case, it doesn't want to turn on dark mode at all, even after toggling and refreshing three times. Windows 10 1809 LTSC, latest release from GitHub.

**Comment by dusansimic** [comment]
@JoelFeiner when you start Caprine, the HTML tag should have `dark-mode` class and `__fb-dark-mode` class among others. Please check that you have those classes when you start Caprine and that Dark mode option is checked. If those, classes are present (both of those classes) and Messenger is not dark, please let me know.

@supra107 your issue is unrelated to this. Dark mode fix is not yet available in releases on GitHub. Please wait for the next update of Caprine to get the fix. Author of this issue has the dark mode fix because they compiled Caprine themselves.

**Comment by John15321** [comment]
Hi, I have the same issue on Manjaro with Caprine installed from both Manjaro Official Repos and Snap
![image](https://user-images.githubusercontent.com/56229312/104856952-91c93500-5915-11eb-9bb6-ddab68f60777.png)

**Comment by JoelFeiner** [comment]
> @JoelFeiner when you start Caprine, the HTML tag should have `dark-mode` class and `__fb-dark-mode` class among others. Please check that you have those classes when you start Caprine and that Dark mode option is checked. If those, classes are present (both of those classes) and Messenger is not dark, please let me know.
> 
> @supra107 your issue is unrelated to this. Dark mode fix is not yet available in releases on GitHub. Please wait for the next update of Caprine to get the fix. Author of this issue has the dark mode fix because they compiled Caprine themselves.

This is what it shows:

![image](https://user-images.githubusercontent.com/20820071/104947769-3f762b80-598a-11eb-8588-1870c072cba6.png)

So I do see the `dark-mode` class. I also see Dark Mode checked in the View menu. But it is not dark.

When I turn off and turn on Dark Mode, it has the `__fb-dark-mode` class. It looks like that must be missing on startup for some reason.

![image](https://user-images.githubusercontent.com/20820071/104947888-6a607f80-598a-11eb-9040-15e1bdb6ecf5.png)

**Comment by 1nikolas** [comment]
Hey I have this issue too. For some reason `__fb_dark_mode` isn't added although `dark-mode` is. I have version 2.51.2
![image](https://user-images.githubusercontent.com/30593419/105029555-29846b80-5a5b-11eb-9ebb-2144c89759eb.png)

**Comment by js-beaulieu** [comment]
@John15321 This particular issue is a bit different - @JoelFeiner built from `master` himself. The snap and manjaro package are on the latest release tag.

See my previous issue about that same issue you have. It's reportely already fixed and will be pushed with the next release. https://github.com/sindresorhus/caprine/issues/1526

**Comment by dusansimic** [comment]
@js-beaulieu is right. The fix is not yet released in Caprine. We are expecting a release soon which will fix several issues alongside dark mode, some keybindings and menu options however there are still more issues to fix since the new desing is completely different from the old one.

@JoelFeiner thanks for the info. I've run Caprine from master a couple of times and I sometimes do experience it and sometimes I don't, which is really weird. I'll see what could be done about that and what might be causing the issue.

**Comment by mquevill** [comment]
I just installed Caprine v2.52.0 (on Linux Mint 20.1, from .deb) and the dark mode is not persistent. Every time I start it up, it goes to light mode (even though "Dark Mode" is ticked). I have to turn dark mode off and on again for it to work.

**Comment by JoelFeiner** [comment]
I've edited the title to indicate that this is not the current released version. The currently released version does NOT support dark mode. A fix is in progress.

**Comment by Amandaville** [comment]
Same with the new 2.52.0 .deb release on MX

**Comment by JoelFeiner** [comment]
I can confirm the issue persists on `main`.

**Comment by dusansimic** [comment]
We've released a new version (2.52) which adds dark mode but the issue of dark mode not being enabled on startup is still there. I'll try to research this issue more however any help regarding this is very welcome.

Regarding the name of the issue, I'll revert it back to the old one since it is now regarding the latest release of Caprine, not the development branch.

**Comment by jlanzobr** [comment]
Can confirm that this bug remains present on Arch Linux, as of Caprine 2.52.0-1.

**Comment by RickSlashee** [comment]
Bug remains on Manjaro KDE with Caprine 2.51.2-1

**Comment by RickSlashee** [comment]
> Can confirm that this bug remains present on Arch Linux, as of Caprine 2.52.0-1.

Bugs are solved if you work with the AppImage

**Comment by ElArtista** [comment]
Using latest build on Arch Linux, dark mode does not work even when turning it off and on again

**Comment by matthewstrasiotto** [comment]
I think it's been fixed in main as of #1552 , but that hasn't been published as a release yet. For me, it's annoying enough that I considered building from source, but I don't really want to.

@dusansimic do you think the head is ready for a patch release? I'd bet people are going to keep rasing this as a duplicate issue until the version they can install using their package manager includes the startup prefs fix.

**Comment by dusansimic** [comment]
@matthewstrasiotto I don't think this issue is fixed by the pr you mentioned. It is an unrelated pr. I've managed to fix it but it's not a pretty solution. I'll submit the pr for review and we'll see how it goes.
