### ISSUE TITLE
Caprine on macOS requiring high performance GPU 100% of the time

### ISSUE THREAD

**Issue by dudeofawesome** [sindresorhus/caprine#155]
I just recently got a new MacBook Pro 2016 (up from a MacBook Air), and now Caprine is requiring the high performance GPU to be on 100% of the time, which significantly reduces battery life. As my MacBook Air didn't have a discrete GPU, I don't know if this is a new issue.

![image](https://cloud.githubusercontent.com/assets/1683595/21670922/4261ed88-d2d5-11e6-98b3-c781e944b455.png)

I believe this is actually an issue with Facebook Messenger on Chrome, not Caprine itself, as when I opened [m.me](https://m.me) in Chrome, it made Chrome start using the dGPU. However, opening [m.me](https://m.me) in Safari doesn't force the dGPU.

I'm wondering if there is a way that we could disable Caprine from ever using the dGPU, as I don't see a reason it should ever need it, except maybe for the new games.

**Comment by aluxian** [comment]
I think I fixed this in MFD with `app.disableHardwareAcceleration `: https://github.com/aluxian/Messenger-for-Desktop/commit/e4c8138c93935cbc1e1312161ed0b6efe56ac01b

Not sure what its side-effects are though.

**Comment by veniversum** [comment]
Can we verify that this is still an issue? 

`NSSupportsAutomaticGraphicsSwitching` is currently set to `true` in `Info.plist` on macOS builds, probably as a result of switching to electron-builder in 8f430bc. [This allows using integrated GPU as preferred option instead of dGPU](https://github.com/daveygm/brackets-shell/commit/c238da5b300edb075e9617a76daa5d288960102f).

**Comment by dudeofawesome** [comment]
I just updated to 2.3.1.437

**Comment by gklka** [comment]
This is still an issue.

**Comment by abhivs** [comment]
Still an issue for me as well. Saw the same issue with the latest version of Mailplane, so likely something to do with Electron in general.

**Comment by Lownin** [comment]
Still an issue.  I contacted Mailplane support and they fixed it in the next release very quickly.  Issue still remains in Caprine.

**Comment by whitecrownclown** [comment]
@Lownin @simonhaenisch Disabling `hardware acceleration` should work.
![hw-acceleration](https://user-images.githubusercontent.com/8309417/53636751-ea13c280-3c29-11e9-844a-30e499b62aea.png)
![no-hw-acceleration](https://user-images.githubusercontent.com/8309417/53636754-ebdd8600-3c29-11e9-99f8-ba800e6b43b7.png)
<img width="454" alt="caprine-preferences" src="https://user-images.githubusercontent.com/8309417/53636793-07e12780-3c2a-11e9-915b-e41264fd733f.png">

**Comment by Lownin** [comment]
Confirmed, that does the trick.
