### ISSUE TITLE
Message replies and user mentions broken

### ISSUE THREAD

**Issue by kiernann** [sindresorhus/caprine#1664]
There appears to be a change to the underlying web interface that may have broken some features.

* Typing `@` no longer prompts the mention of a user.
* Replying send the message without the original message for context.
* Dark mode no longer stays active after restart and cannot be re-enabled.

**Comment by mquevill** [comment]
Some of the modal windows (e.g. the `@` popup) were broken, but commits have been made to the `main` branch. Additionally, there were changes made to the dark mode options that should help address your issue. Hopefully these should be fixed with the next released version.

**Comment by dusansimic** [comment]
@kiernann please download the latest release, the issue should be solved.

**Comment by kiernann** [comment]
I've installed `caprine_2.54.1_amd64.deb` and the problem persists.

**Comment by dusansimic** [comment]
These issues should be solved by now. Please check with the latest release.
