### ISSUE TITLE
Dark mode obscures message text sent by recipients

### ISSUE THREAD

**Issue by Steppenwolf86** [sindresorhus/caprine#1760]
---

Caprine 2.54.1
Electron 10.1.5
linux 5.11.0-41-generic
Locale: en-GB

**Comment by Steppenwolf86** [comment]
![image](https://user-images.githubusercontent.com/85005316/145152322-47e55399-5399-4657-9b0f-fbc9b5ad968b.png)

![image](https://user-images.githubusercontent.com/85005316/145152382-cc74ff5f-876e-4b5e-8cdb-e570dbd05a09.png)

**Comment by mattnoir** [comment]
it has been fixed in newer version

**Comment by dusansimic** [comment]
@Steppenwolf86 please update to the latest version of Caprine (2.55.1). Keep in mind that there is one more issue remaining #1751 but a fix is ready for it and it will be available in next release #1757.
